### PR TITLE
[FEATURE] Use optgroups for CType field

### PR DESCRIPTION
**Pull request by georgringer**
Group all container items in the CType select by using an optgroup.

Resolves: #68

### CODE REVIEW

**Comment by davidsteeb** [comment]
I think this should be configurable. A default „container“ group that I can change for individual container element types makes most sense. I can think of a number of use cases I might want a particular element to be sorted into a different group.

**Comment by georgringer** [comment]
@davidsteeb do you wanna change that?

**Comment by davidsteeb** [comment]
I’ll try tonight if no one is faster than me :-)

**Comment by georgringer** [comment]
@davidsteeb what about turning the `addContainer` into using a configuration object? there are already tons of options

**Comment by achimfritz** [comment]
@georgringer we agree and i make a new issue : #76

**Comment by achimfritz** [comment]
@georgringer i create an new mr with your commit and Configuration-Object
Thanks for Patch

s #89

**Pull request closed without merging**
