### PR TITLE
[TASK] Avoid usage of deprecated QueryBuilder::execute() in TYPO3 v12

### PR DESCRIPTION
**Pull request by kevin-appelt**

### CODE REVIEW

**Comment by achimfritz** [comment]
do you forget some use statements?
Screenshot from 2023-04-27 17-51-54

**Comment by kevin-appelt** [comment]
@achimfritz Should be fixed and rebased with current master now.

**Comment by achimfritz** [comment]
we need also adapt phpstan rules (s. Build/phpstan<TYPO3 Version>.neon)

 s. https://github.com/b13/container/actions/runs/4828271563/jobs/8609709099

s. https://github.com/b13/container/blob/master/.github/workflows/ci.yml for usage of the runTest.sh Script, so you can test your changes

**Comment by kevin-appelt** [comment]
@achimfritz Would be great to receive some feedback. Running the tests gave me a hard time and couldn't be executed entirely, but I guess it should be fine now.

**Comment by kevin-appelt** [comment]
Rebased my patch to get the ci fix adjustments. Hope that helps to get the tests green :)

**Review by achimfritz — APPROVED** [review]
👍

**Pull request merged**
