### PR TITLE
[TASK] Use associative array keys for TCA items

### PR DESCRIPTION
**Pull request by kevin-appelt**
This avoids deprecation messages in the TYPO3 log.
Feature is described here: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.3/Feature-99739-AssociativeArrayKeysForTCAItems.html
Deprecation is described here: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.3/Deprecation-99739-IndexedArrayKeysForTCAItems.html

### CODE REVIEW

**Comment by achimfritz** [comment]
Hi @kevin-appelt , thanks for PR, can you rebase with master, to see all tests still works?

**Comment by kevin-appelt** [comment]
@achimfritz I hope GitHub did what I expected GitHub to do :D

**Comment by kevin-appelt** [comment]
It did not ... manually rebased and force pushed my changes now. Hope that the test will pass now.

**Comment by achimfritz** [comment]
seems this produce warnings (at least with TYPO3 11 and PHP 8.1):
B13 Container Tests Acceptance Backend ContentDefenderCest canCreateChildIn2ColsContainerWithNoContentDefenderRestrictionsDefined fail

**Comment by achimfritz** [comment]
the warnings are not solved (TYPO3 11, PHP8)

Core: Error handler (BE): PHP Warning: Undefined array key 1 in /var/www/container/.Build/Web/typo3/sysext/backend/Classes/View/PageLayoutContext.php line 251

```
    public function getContentTypeLabels(): array
    {   
        if (empty($this->contentTypeLabels)) {
            foreach ($GLOBALS['TCA']['tt_content']['columns']['CType']['config']['items'] as $val) {
                $this->contentTypeLabels[$val[1]] = $this->getLanguageService()->sL($val[0]);
            }
        }
        return $this->contentTypeLabels;
    }
```
looks as we need TYPO3-Version Condition in Registry?

**Comment by kevin-appelt** [comment]
@achimfritz Would be great to receive some feedback. Running the tests gave me a hard time and couldn't be executed entirely, but I guess it should be fine now.

**Review by achimfritz — APPROVED** [review]
👍 , thanks

**Pull request merged**
