### PR TITLE
[BUGFIX] Rename Record.html to RecordDefault.html

### PR DESCRIPTION
**Pull request by kevin-appelt**
See: https://review.typo3.org/c/Packages/TYPO3.CMS/+/69493/

Resolves: #161

### CODE REVIEW

**Comment by juergen-venne** [comment]
This patch will break functionality in TYPO3 < 10.4.18 and < 11.3.0:
RecordDefault is never rendered, instead Record.html of ext:backend is rendered.

**Comment by georgringer** [comment]
so what about just duplicating the file instead of renaming?

**Comment by georgringer** [comment]
will be fixed with https://github.com/b13/container/pull/170

**Comment by o-ba** [comment]
Hi, since this had been fixed in #170, I'll close this issue. In case you still encounter this exception, please create a new issue with a link to this on.

**Pull request closed without merging**
