### PR TITLE
[BUGFIX] enable recursive copy of multiple containers via DataHandler

### PR DESCRIPTION
**Pull request by DavidHedden**
Use `copyMappingArray` instead of first key from `$pasteDatamap`, since it could include multiple id's.

To clarify where this is a problem. When copying multiple containers via the data handler while using `'action' => 'paste'` instead of a target. The `$pasteDataMap` provided to the hook will not clear itself after performing each copy of a container. So the first provided container will be used as a target for all the child records.

### CODE REVIEW

**Comment by achimfritz** [comment]
Hi @DavidHedden , looks good, thanks, can you also write a functional test?

**Comment by DavidHedden** [comment]
Hi @achimfritz, i added a test were it's validated that the child records are in the correct container.
I left out testing for correct amount of child records, sorting etc., since they are covered already.

**Comment by DavidHedden** [comment]
Fixed the formatting issues. Should've seen that there is a script for that.

**Review by achimfritz — APPROVED** [review]
👍 , very cool, thanks

**Pull request merged**
