### PR TITLE
[TASK] allow grouping of children

### PR DESCRIPTION
**Pull request by juergen-venne**
Using the ContainerProcessor with this TypoScript will group the children so one can iterate over them. Please note the dot in "as = childs.children_200"
```
tt_content.b13-2cols-with-header-container {
    templateName = 2ColsWithHeader
    templateRootPaths {
        10 = EXT:container/Resources/Private/Contenttypes
    }
    dataProcessing {
        200 = B13\Container\DataProcessing\ContainerProcessor
        200 {
            colPos = 200
            as = childs.children_200
        }
        201 = B13\Container\DataProcessing\ContainerProcessor
        201 {
            colPos = 201
            as = childs.children_201
        }
    }
}
```

will group the children in fluid template in variable "childs":
```
childs 
    children_200
    children_201
```
Allows to iterate over them using a for-loop
```
<f:for each="{childs}" as ="childRecords">
    <f:for each="{childRecords}" as="record">
        {record.header} <br>
        <f:format.raw>
            {record.renderedContent}
        </f:format.raw>
    </f:for>
</f:for>
```

### CODE REVIEW

**Comment by achimfritz** [comment]
@juergen-venne  What is the use case to iterate over children in different colPos's ?

**Comment by juergen-venne** [comment]
I'm using a responsive layout with up to 6 cols. I use the same FE-template for all of that cols, so I simply want to iterate over the columns. I need the column count to dynamically create HTML-classes for different styling issues, too.

**Comment by achimfritz** [comment]
Why not use 6 different FE-Templates? (so you save also the dynamically creation of your classes, because on each template, you know already the column count). If you not agree with my suggestion, you can still use your own DataProcessor. We do not wanna bloat our code with too many Special Cases/Features that are not really needed. So I think we should not merge this PR.

**Comment by juergen-venne** [comment]
6 Templates mean redundant code. I don't want to use partials either. They slow down the rendering process. 
Ok, I thought this might be interesting for others, too. So I will simply add a static typoscript-Variable to my container setup to get the count of my columns.
`
tt_content.lns-1col-container < lib.contentElement
tt_content.lns-1col-container {
  templateName = GenericContainer
  templateRootPaths.10 = EXT:lns_grid_container/Resources/Private/Templates
  variables.colCount = TEXT
  variables.colCount.value = 1
  dataProcessing {
    10 = Lns\LnsGridContainer\DataProcessing\FlexFormProcessor
    10 {
      as = flexform
    }
    210 = B13\Container\DataProcessing\ContainerProcessor
    210 {
      colPos = 210
      as = col1
    }
  }
}
`

**Comment by fgerards** [comment]
this is an essential feature to b13/container - also, it should be possible to to container elements with dynamic amount of columns - like Flux/FluidTYPO3 can do. without that, a "Tabs" element etc. is not really doable and lots of template code is doubled - this is not how TYPO3 used to be (e.g. with Templavoila it was possible, with FluidTYPO3 it is possible etc.) - would be nice to adhere the standard of complexity we love in TYPO3.

**Pull request closed without merging**
