### PR TITLE
[BUGFIX] Fix integrity sorting in page with nested containers

### PR DESCRIPTION
**Pull request by extcode**
Relates: #458

### CODE REVIEW

**Comment by achimfritz** [comment]
i do not understand this example, because integrity is broken, and this looks not like a sorting problem?
if i import you dataset i have
uid 2 and uid 5 as unused elements
after running sorting-in-page i have uid 5 unused (and uid 2 is used, this should not be changed by sorting)
can you please construct a non-broken dataset?

**Comment by extcode** [comment]
I will take another look at the test setup. This is a customized example from a current project. From our point of view, the data in this project is not repaired correctly, so that moving content elements is not possible in certain situations.

**Comment by extcode** [comment]
This is the scenario in our project. I hope that I now have correctly reduced the IDs and sorting to small numbers. _The uids of the containers and content elements are 6 digits in the project. The numbers for the sorting are mostly 4 digits, because there is a lot of content on the pages._ 

We cannot move the container with id:6 over the one with id:4, because for the calculation of the last child the sorting is not returned from the element id:3 but from id:2.

TYPO3 should therefore move id:6 to id:2. From TYPO3's point of view, however, nothing needs to be done here because sorting:3 of id:2 is greater than sorting:2 of id:6.

 ```ditaa {cmd=true args=["-E"]}
+---------------------------------------------------+
| id:1                                              |
| sorting:1                                         |
| colPos:0                                          |
|-------------------------+-------------------------+
|                         | id:2                    |
|                         | sorting:2               |
|                         | colPos:202              |
|                         +------------+------------+
|                         |            | id:3       |
|                         |            | sorting:5  |
|                         |            | colPos:202 |
+-------------------------+------------+------------+

+---------------------------------------------------+
| id:4                                              |
| sorting:3                                         |
| colPos:0                                          |
|-------------------------+-------------------------+
|                         | id:5                    |
|                         | sorting:4               |
|                         | colPos:202              |
+-------------------------+-------------------------+

+---------------------------------------------------+
| id:6                                              |
| sorting:6                                         |
| colPos:0                                          |
|-------------------------+-------------------------+
|                         | id:7                    |
|                         | sorting:7               |
|                         | colPos:202              |
+-------------------------+-------------------------+
```

As far as I can see, the command container:sorting checks the integrity of the containers id:1, id:4 and id:6.

The command container:sorting-in-page checks the containers one below the other and should correct the sorting for id:4 and following, because id:3 has set a higher value for sorting.
As I said, this does not happen because the last child of id:1 is not actually fetched.

With commit d1381f4 the test setup should be fixed. I debugged the $rows before and after running the command and get following changes for sorting (->). The colPos doesn't change anymore:

 ```ditaa {cmd=true args=["-E"]}
+---------------------------------------------------+
| id:1                                              |
| sorting:1                                         |
| colPos:0                                          |
|-------------------------+-------------------------+
|                         | id:2                    |
|                         | sorting:2               |
|                         | colPos:202              |
|                         +------------+------------+
|                         |            | id:3       |
|                         |            | sorting:5  |
|                         |            | colPos:202 |
+-------------------------+------------+------------+

+---------------------------------------------------+
| id:4                                              |
| sorting:3 -> 261                                  |
| colPos:0                                          |
|-------------------------+-------------------------+
|                         | id:5                    |
|                         | sorting:4 -> 517        |
|                         | colPos:202              |
+-------------------------+-------------------------+
```

**Review by achimfritz — APPROVED** [review]
👍

**Pull request merged**
