### PR TITLE
[TASK] Provide default icons for multi column containers

### PR DESCRIPTION
**Pull request by davidsteeb**
Related: #42

### CODE REVIEW

**Comment by georgringer** [comment]
@davidsteeb can you add a 1col icon as well? thx

**Comment by bmack** [comment]
@georgringer WHO IS DOING 1 COL CONTAINERS????? ;)

**Comment by davidsteeb** [comment]
I’ll try to get one tomorrow.

**Comment by davidsteeb** [comment]
Thanks to Laura we now have a one-column container icon.

**Pull request merged**
